FROM python:3.11 

ENV PYTHONNUNBUFFERED=1

WORKDIR /code

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . . 

EXPOSE 8000

CMD ["python","manage.py","runserver"]

CMD ["python","manage.py","makemigrations"]
CMD ["python","manage.py","migrate"]

CMD ["python","manage.py","makemigrations api"]
CMD ["python","manage.py","migrate api"]

CMD ["python","manage.py","collectstatic"]