# Generated by Django 4.2.1 on 2023-05-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_distance_destination_distance_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='source',
        ),
    ]
