# Generated by Django 4.2.1 on 2023-05-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_distance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='api.address'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='api.address'),
        ),
    ]
